name: Pogues CI

on: [push]

jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn
      # Run tests & build sonar reports
      # - run: yarn test
      # Build lib
      - run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

#  sonarcloud:
#    runs-on: ubuntu-latest
#    needs: test-build
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Download coverage artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: coverage
#          path: coverage
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
#    needs: test-build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.8.4
        with:
          images: inseefr/pogues # list of Docker images to use as base name for tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/pogues:latest' || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
