name: Pogues Test CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn
      # Run tests & build sonar reports
      - run: yarn test
      # Build lib
      - run: yarn build
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
